### ISSUE TITLE
SolrProvider.GetHelper is obsolete

### ISSUE THREAD

**Issue by DanielLavrushin** [dataweaversio/SmartSolrSchema#1]
Hi Mark,

I am trying to use your library in my sitecore 9.3 (Sitecore 9.3.0 rev. 003498 (OnPrem)_single.scwdp) project and I found an issue with some obsolete code - so your library does not work in v9.3
When trying to use it with Sitecore.ContentSearch.SolrProvider dll v6.0.0 it fails with an exceptoin "unable to find the constructor".

After digging the code I found out the issue lies in 'Sitecore.ContentSearch.SolrProvider.Pipelines.PopulateSolrSchema.PopulateFields' class of the sitecore library.

Both constructor and GetHelper are marked now as obsolete and are not used anymore in sitecore
```
[Obsolete("Please use PopulateFields(IPopulateHelperFactory) constructor instead")]
public PopulateFields()
```

```
[Obsolete("This method is not in use anymore, use IPopulateHelperFactory.GetPopulateHelper instead")]
protected virtual ISchemaPopulateHelper GetHelper(SolrSchema schema)
```

So I manage to get it work by replacing your PopulateFields helper class with this code:

```
  public class PopulateFields : Sitecore.ContentSearch.SolrProvider.Pipelines.PopulateSolrSchema.PopulateFields
    {
        private readonly IPopulateHelperFactory populateHelperFactory;
        public PopulateFields(IPopulateHelperFactory populateFactory) : base(populateFactory)
        {
            populateHelperFactory = populateFactory;
        }

        public override void Process(PopulateManagedSchemaArgs args)
        {
            var solrIndex = (args.Index as SolrSearchIndex);
            var schema = (SolrIndexSchema)solrIndex.Schema;
            var helper = new PopulateSolrSchemaHelper(schema.SolrSchema);

            var solrConnector = (ISolrConnector)solrIndex.GetType().GetProperty("SolrConnector", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(solrIndex, null);
            if (solrConnector != null)
            {
                foreach (string core in args.Cores)
                {
                    var operations = solrConnector.OperationsFactory.GetSolrOperations(core);
                    var elements = helper.GetAllFields().ToList();
                    operations.UpdateSchema(elements);

                }
            }
        }
    }
```

Do you think this is the right approach? So far I got back all missing fields in my solr managed schema...

**Comment by markgibbons25** [comment]
Hi Daniel, if you look here https://github.com/dataweaversio/SmartSolrSchema/blob/2c08dc2aa176828a1485e4265aaa87d9637ec37b/src/SmartSolrSchema/Pipelines/SolrProvider/PopulateSolrSchemaHelper.cs#L342 you can see that I'm doing a conditial compile for .NET 4.8 . I presume you're on .NET 4.7 so are hitting this issue? I forgot that Sitecore 9.3 supports both 4.7 and 4.8. In this case it might be quicker for you to change that directive to NET47 and recompile.

**Comment by DanielLavrushin** [comment]
oh yes, I am on net 4.7.2 - good point. Not sure I can switch to 4.8 though, as we have some libraries that concider net48 as sitecore 10. I will try to recompile it with net47 constant

**Comment by sgigras1973** [comment]
Hi,

This is not working, i am doing wrong please correct me.
public class DefaultPopulateHelperFactory : IPopulateHelperFactory
    {
        public ISchemaPopulateHelper GetPopulateHelper(SolrSchema solrSchema) => new CustomSchemaPopulatorHelper(solrSchema);
    }
    public class CustomSchemaPopulator : PopulateFields
    {
        //Need to check [shekhar]
        private readonly DefaultPopulateHelperFactory populateHelperFactory;
        public CustomSchemaPopulator(DefaultPopulateHelperFactory populateFactory) : base(populateFactory)
        {
            populateHelperFactory = populateFactory;
        }
        public override void Process(PopulateManagedSchemaArgs args)
        {
            var solrIndex = (args.Index as SolrSearchIndex);
            var schema = (SolrIndexSchema)solrIndex.Schema;
            var helper = new CustomSchemaPopulatorHelper(schema.SolrSchema, args.Index.Name);

            var solrConnector = (ISolrConnector)solrIndex.GetType().GetProperty("SolrConnector", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(solrIndex, null);
            if (solrConnector != null)
            {
                foreach (string core in args.Cores)
                {
                    var operations = solrConnector.OperationsFactory.GetSolrOperations(core);
                    var elements = helper.GetAllFields().ToList();
                    operations.UpdateSchema(elements);
                }
            }
        }
    }

**Comment by sgigras1973** [comment]
Previously we are using with 9.2
    public class CustomSchemaPopulator : PopulateFields
    {
        protected string IndexName;

        public override void Process(PopulateManagedSchemaArgs args)
        {
            IndexName = args.Index.Name;
            base.Process(args);
        }

        protected override ISchemaPopulateHelper GetHelper(SolrNet.Schema.SolrSchema schema)
        {
            Assert.ArgumentNotNull(schema, "schema");
            return new CustomSchemaPopulatorHelper(schema, IndexName);
        }
    }

but currently using 10.2, i am using Sitecore.ContentSearch 9 version, frameowrk 4.8

**Comment by markgibbons25** [comment]
@sgigras1973 can you make sure you have changed to use the [SmartSolrSchema.SC101](https://www.nuget.org/packages/SmartSolrSchema.SC101) nuget package and ensure that you have App_Config/Modules/SmartSolrSchema/PopulateSolrSchema.config enabled. No custom code should be required.

**Comment by sgigras1973** [comment]
is not possible to use though code. if we change it then we need to explain to client.

please provide through code
